// generated by stringer -type=Cislovacka; DO NOT EDIT

package num

import "fmt"

const _Cislovacka_name = "PNPrMcVcC19C0cCCcCC"

var _Cislovacka_index = [...]uint8{0, 1, 2, 4, 6, 8, 11, 13, 15, 17, 19}

func (i Cislovacka) String() string {
	if i >= Cislovacka(len(_Cislovacka_index)-1) {
		return fmt.Sprintf("Cislovacka(%d)", i)
	}
	return _Cislovacka_name[_Cislovacka_index[i]:_Cislovacka_index[i+1]]
}
