// Code generated by "stringer -type Cxx -trimprefix Cxx"; DO NOT EDIT.

package engine

import "strconv"

const _Cxx_name = "PNPrMcVcC19C0cCCcCC"

var _Cxx_index = [...]uint8{0, 1, 2, 4, 6, 8, 11, 13, 15, 17, 19}

func (i Cxx) String() string {
	if i >= Cxx(len(_Cxx_index)-1) {
		return "Cxx(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Cxx_name[_Cxx_index[i]:_Cxx_index[i+1]]
}
